In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [22]:
from sklearn.datasets import make_classification
X, y  = make_classification(n_samples=100000,n_features = 5, n_classes = 2, random_state=99)

In [23]:
X

array([[ 0.72645624,  1.13696874,  0.57208377, -1.04838209,  1.20472978],
       [ 0.98406449,  1.62825087,  1.50348388, -1.7135701 ,  0.93973011],
       [-0.16704194,  0.08909646,  0.98030168, -0.92636963, -3.03110089],
       ...,
       [ 0.32577461,  0.76447463, -1.03645844, -1.31810508, -1.46017152],
       [ 0.38883278,  0.51271593, -0.93541027, -0.24194359,  1.39784495],
       [ 0.21116085,  0.53315826, -0.71236285, -0.97973081, -1.24219154]])

In [24]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,y, test_size = 0.3, random_state =42)

In [41]:
X_train.shape

(70000, 5)

In [11]:
y_train.shape

(700,)

In [26]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [27]:
knn.score(X_train,y_train)

C:\Users\acer\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.9287571428571428

In [28]:
y_pred = knn.predict(X_test)

C:\Users\acer\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [29]:
y_pred

array([1, 0, 0, ..., 1, 0, 0])

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

0.908

In [31]:
confusion_matrix(y_test, y_pred)

array([[13359,  1755],
       [ 1005, 13881]], dtype=int64)

In [32]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.93      0.88      0.91     15114\n           1       0.89      0.93      0.91     14886\n\n    accuracy                           0.91     30000\n   macro avg       0.91      0.91      0.91     30000\nweighted avg       0.91      0.91      0.91     30000\n'

In [40]:
knn2 = KNeighborsClassifier(algorithm="kd_tree")
knn2.fit(X_train,y_train)

KNeighborsClassifier(algorithm='kd_tree')

In [47]:
knn2.score(X_train,y_train)

C:\Users\acer\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.9287571428571428

In [48]:
y_pred = knn2.predict(X_test)
accuracy_score(y_test,y_pred)

C:\Users\acer\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.908

In [45]:
knn3 = KNeighborsClassifier(algorithm="ball_tree")
knn3.fit(X_train,y_train)

KNeighborsClassifier(algorithm='ball_tree')

In [49]:
knn3.score(X_train,y_train)

C:\Users\acer\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.9287571428571428

In [50]:
y_pred = knn3.predict(X_test)
accuracy_score(y_test,y_pred)

C:\Users\acer\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.908